### ISSUE TITLE
要望何点か

### ISSUE THREAD

**Issue by m-sigepon** [unity3d-jp/NormalPainter#1]
さっそく試させていただきました！
ブラシが、カーブで調整できるのが神がかっています…。
ちょっと触ってみて何点か対応お願いしたい要望があります。

・ブラシのサークルの描画
このようにブラシのサークルを描画するのは難しいでしょうか？
影響範囲はグラデーションで描画されているのですが、いまいち範囲の感覚を掴めないのと頂点表示をオフにしてしまうと範囲が分からなくなるためサークル表示に対応できればと思います。
![default](https://user-images.githubusercontent.com/26161297/27502196-68802850-58ad-11e7-84f1-726de6bb2e1b.jpg)

・ポリゴンの切れ目の頂点の選択＆同一座標の頂点への法線のコピー＆ペースト
例えば、首のつなぎ目の法線を合わせるためにHeadオブジェクトのポリゴンの切れ目の法線を選択して、Neckオブジェクトの同一座標の頂点に法線をコピーするというようなことをよくDCCツールで行っています。
なので、選択しているオブジェクトの切れ目の頂点を選択する機能が欲しいです。

また、それらの接続頂点に対してスムーズを掛けることもありますが中間値になるとおかしくなる場合もあり片側の法線をコピーして適用するというのを行うことがあります。
なので、単純に同一座標の頂点に対して法線をコピーする機能が欲しいです。
こちらパット見た限り無かったと思うのでうが、どこかのEditで可能でしょうか？

・ブラシサイズ調整にショートカット割当
ブラシのサイズを調整するのにPhotoshopと同じように[と]キーでサイズ変更できるようにできたら良いなと思いました。

・Display項目の一括オンオフ
Display項目の全ての項目を一括でオンオフして表示非表示できるボタンを追加できないでしょうか。

対応ご検討宜しくお願い致します。
素晴らしいツールをありがとうございます！

**Comment by i-saint** [comment]
フィードバックありがとうございます。
どれも尤もだと思うので次のリリースまでに対応しておきます。

一点、
・ブラシサイズ調整にショートカット割当
これは Scene View をフォーカスした状態で Shift + マウスホイールで変えられるようになっています。Ctrl + マウスホイールで Strength も変わります。
(NormalPainter ウィンドウをフォーカスしている場合はマウスイベントが飛んでこないようで、現状反応しないようです。対策を考えます)

なお、これらの操作は NormalPainter ウィンドウ下部に tips として表示しています。気づきにくいと思われますが…。 
他に tips として表示してる機能としては選択の加算+減算があります。メタセコイアを真似て Shift + 選択 で選択の加算、Ctrl + 選択 で選択の減算ができるようになっています。

**Comment by m-sigepon** [comment]
ブラシサイズのショートカットあったのですね。
Tipsの方でてたの気づきませんでした…、確認してみます！

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/NormalPainter/releases
新しいバージョンをリリースしました。上記要望はカバーしているはずです。
ファイルの構成が若干変わってるので、古いのは消してから import した方がいいかもしれません。

エッジ (ポリゴンの切れ目) 選択と接続面上の頂点選択が追加されているので、それらで選択してから weld (同一座標頂点への法線コピーを便宜上こう呼んでます) をかけるのを想定しています。
適当に頂点選択、C, Shift+W で切れ目がつながります。

![circle](https://user-images.githubusercontent.com/1488611/27624956-cf293240-5c1d-11e7-9e10-75cf7401461b.png)
![weld](https://user-images.githubusercontent.com/1488611/27624980-e396a0fa-5c1d-11e7-8b94-d52283eb2781.gif)

**Comment by m-sigepon** [comment]
対応ありがとうございます！
画像見た感じ範囲も切れ目選択も良さそうな感じですね。
試してみたいと思います。

**Comment by m-sigepon** [comment]
対応版試してみました。
以下の点改善お願いできるでしょうか。

・ブラシのサイズが数値に対してものすごく巨大になってしまうようです。MeshSyncのようにScaleFactorが必要かと思いました。
![default](https://user-images.githubusercontent.com/26161297/27654078-18246a38-5c7c-11e7-9bfa-463a70e563a0.jpg)

・全ての項目を一括でオンオフという書き方が悪く申し訳ないのですが、All[Tab]のオンオフは、全ての項目の各表示のチェック状態を記憶して一括でオンオフできるようにしたいという感じです。

・Select Edgeがそのままでは選択実行されない（一度SeletAllを押した後にSelect Edgeを押すと選択される）のをSelectEdgeを押すだけで境界の頂点を選択したいです。

・Select Edgeで、境界の頂点ではないハードエッジになってる部分の頂点が選択されてしまうようです。
（境界の頂点の計算の問題か、またはハードエッジの部分はUnity上では頂点が接続されてない扱いになる感じでしょうか？）

・同一座標の頂点に法線をコピーする機能ですが、現状ですと１オブジェクト内での処理となっている？感じでしょうか。
　ちょっとやりたかったこととが上手く伝わらなかったので添付画像も合わせるとこのような処理を行いたい感じです。

　１．まずコピー元の、「M_Face（A)」オブジェクトを選択して、「SelectEdge」で境界の頂点を選択する
　２．次に、選択してるそれぞれ頂点の座標と法線の情報をコピーしてメモリに格納する（法線コピーボタン的なので）
　３．コピー先の「M_HairBack（B)」オブジェクトを選択して、同じように「SelectEdge」で境界の頂点を選択する
　４．ペーストボタン的なので、先程メモリに格納した同一座標の法線の情報を適用する（同一座標の頂点の部分のみコピー処理をしてそれ以外の部分は何もしない）
　５．結果（A)から（B）に境界の頂点の法線がコピーされる

　という感じです。
　Assignの法線コピーとペーストは値が平均化したものを全てに適用するという感じですが
　上記のコピー、ペーストはそうではなくそれぞれの頂点の座標と法線情報を扱う感じです。
![default](https://user-images.githubusercontent.com/26161297/27654088-1dcd0ad0-5c7c-11e7-9519-d5e8d33e32db.jpg)

・複数のオブジェクトを選択して法線編集できるように
　現状複数オブジェクト選択していても、どちらか片方の法線しか編集できないようです。（１オブジェクト内のみの処理しか対応していない？）
　例えば、上記は（A)＞（B)にコピーするという感じですが、（A)と（B）両方共選択した状態で「SelectEdge」を行いそれぞれの境界の頂点を同時に選択し
　「Weld with Smoothing」で同一座標の頂点を平均化した方向に向けるというようなことをしたい感じです。


言葉が足りなかったり伝えきれてない部分が申し訳ないです＞＜
上記で分かりづらいところありましたら質問していただければと思います。

**Comment by i-saint** [comment]
■ブラシのサイズが数値に対してものすごく巨大になってしまう
ううむ。悩ましいですが、ブラシサイズはスライダではなく数値入力、Ctrl+Wheel は割合増減、にして解決しようと思います。極端なスケールの時このままじゃちょっとマズいな、とは思っていたところでした。

■全ての項目を一括でオンオフ～
そのように変更しておきます。

■Select Edgeがそのままでは選択実行されない
現状、選択されている頂点上にあるエッジを調べに行くようになっています。どのエッジか選びたいこともあるのでこの挙動は変えないつもりですが、何も選択されていない場合は全頂点調べる (Selet All + Select Edge と同等) ようにしておきます。

■Select Edgeで、境界の頂点ではないハードエッジ？の部分か謎の頂点が選択されてしまうようです。
推測の通り、ハードエッジ は Unity 上では頂点が分離されているので切れ目と判断されています。
同一座標の頂点もつながってる扱いにして判定することは可能ですが、現行のエッジ選択も使い出はあるので、"Select Hole" とか別のコマンドとして実装しておきます。

この頂点が分離する現象は是非理由を知っておいてほしいです。(過去いろんな人にこの説明をしました…)
DCC ツールではハードエッジや面ごとに分離した UV といったものが当たり前のように扱えますが、これは、DCC ツールが 頂点の位置、法線、UV それぞれに別のインデックスを割り当てているからです。
一方、現行の GPU は 1 つのモデルデータにつき 1 つのインデックスしか使えません。位置、法線、UV 等全てを同じインデックスで扱う必要があります。なので、ハードエッジや分離 UV がある場合は頂点を分離することでなんとか見た目を一致させています。
頂点数が DCC 側とランタイム側で微妙に異なるのを目にすることは多いと思いますが、こういった理由によるものです。これは Unity に限らず、リアルタイム系アプリケーションはほぼ全てそういう挙動になっているはずです。

■同一座標の頂点に法線をコピーする機能 ＆ 複数のオブジェクトを選択して法線編集できるように
オブジェクトをまたぐ編集が欲しくなるのはよくわかるのですが、実装がすごく大変で、何かいいアイデアが思いつかない限り対応しないと思います。現状は 1 オブジェクトにまとめたモデルを用意するなど、なんとかモデル側での対処をお願いします。

**Comment by m-sigepon** [comment]
>ううむ。悩ましいですが、ブラシサイズはスライダではなく数値入力、Ctrl+Wheel は割合増減、にして解決しようと思います。極端なスケールの時このままじゃちょっとマズいな、とは思っていたところでした。

スライダはスライダで使いやすいので％テージみたいなので調整難しいでしょうか？
ブラシサイズの値[1]SceneScale[50]%
ブラシサイズにSceneScaleに乗算するイメージです。これなら大きめの値でもSceneScaleの値を調整すれば問題ないかと

また、Ctrl+Wheelのショートカットなのですがマウスでやってたので気づかなかったのですが
ペンタブだとホイールが無いのでサイズ変更できないため、メタセコのマグネットツールのようにShift+ドラッグでサイズ変更するのは難しいでしょうか？


>同一座標の頂点もつながってる扱いにして判定することは可能ですが、現行のエッジ選択も使い出はあるので、"Select Hole" とか別のコマンドとして実装しておきます。

別機能として実装ありがとうございます！
補足の説明もありがとうございます！まともに情報持ったらめちゃくちゃ重いですからね…。
仕様が把握できて助かりました。
GPUの1頂点１インデックス心に留めておきたいと思います。


>オブジェクトをまたぐ編集が欲しくなるのはよくわかるのですが、実装がすごく大変で、何かいいアイデアが思いつかない限り対応しないと思います。現状は 1 オブジェクトにまとめたモデルを用意するなど、なんとかモデル側での対処をお願いします。

基本的には、オブジェクトが別れてると負荷が増えるので１オブジェクトに統合しているのですが
顔のようなモーフターゲットを仕様してる部分は別オブジェクトにする必要があるため、どうしても１オブジェクトにできないのです…。
そのため、境界の頂点の法線を合わせたいという要望を出した次第でした。

２つのオブジェクトを同時に編集するというのは、実装が難しそうなのでとりあえず保留するとして
１つのオブジェクトで選択した頂点の法線情報をコピーするというのは、もしメモリ上に保持したまま別のものに適用するのが難しければ、一時ファイルとしてnormalCopy.tmpみたいなテキストファイルに必要情報をNormalPainterのフォルダに出力して、別のオブジェクトでペーストボタンをおした時にはそのファイルから情報を読み込んでくるというような動作だとどうでしょうか？

他になにかうまい方法があればよいのですが…。

**Comment by m-sigepon** [comment]
選択関連で必要そうな機能２つほど追加です。

■選択を反転する機能「Select Revert」
選択していた部分を非選択状態にし、選択されていなかった箇所を選択する文字通り選択を反転する機能です。

■法線のロックと解除機能
選択のSave、Loadみたいに、１～5ぐらいのボタンでそれぞれに動かしたくない法線を記憶させてロックしておくボタンが欲しいです。

こういう感じです。
Lock　　[1][2][3][4][5]
Unlock　[1][2][3][4][5]

**Comment by i-saint** [comment]
> スライダはスライダで使いやすいので％テージみたいなので調整
了解です。最大半径 (数値入力) + スライダ、にしてみます。

> オブジェクト間法線コピー
現状の "Apply Welding" を 2 オブジェクト間でできるようにする、では不十分ですかね？これに絞ればたぶん比較的スマートに実装できそうです。

> 選択を反転する機能
入れておきます。

> 法線のロックと解除機能
ブラシの影響を選択範囲に限定する機能であれば既にありますが (Brush -> Mask with Selection)、それでは不十分ですかね？(ものすごく既存機能への影響が広い仕様なのでたじろぎ中…)

**Comment by m-sigepon** [comment]
>現状の "Apply Welding" を 2 オブジェクト間でできるようにする、では不十分ですかね？これに絞ればたぶん比較的スマートに実装できそうです。

上記の例えだと（A）+（B)で2オブジェクトでしたが、それ以上の複数オブジェクトは対応可能でしょうか？
Head+HairBack+Neckのような。
オブジェクト間で法線コピーができればスマートに実装できる形で大丈夫です！

>ブラシの影響を選択範囲に限定する機能であれば既にありますが (Brush -> Mask with Selection)、それでは不十分ですかね？(ものすごく既存機能への影響が広い仕様なのでたじろぎ中…)

なるほどそうなのですね、「Mask with selection」を選択のSave＆Loadと併用する形でいけそうな気がしますので見なかったことにしていただければとｗ

**Comment by i-saint** [comment]
> 上オブジェクト間で法線コピーができればスマートに実装できる形で大丈夫です！

ではそのように実装します。いくつでもいけるようにしておきます。

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/NormalPainter/releases
新しいバージョンをリリースしました。
それなりに動作確認はしているつもりですが、複数オブジェクト間の法線の接合は組み合わせのバリエーションが膨大でカバーしきれてない状況がある可能性が高いです。何か問題があればご一報いただけると幸いです。

Smooth -> Welding2 が複数オブジェクト間の法線の接合になります。Weld Targets のフィールドに
 Hierarchy からドラッグすることでターゲットを設定できます。(下図がその例になってます)
![](https://user-images.githubusercontent.com/1488611/27774461-8a7b624a-5fcd-11e7-9bfb-cf80d4382abb.gif)

**Comment by m-sigepon** [comment]
対応ありがとうございます！！
さっそく今晩確認してみます。

**Comment by m-sigepon** [comment]
最新版試してみました。

![default](https://user-images.githubusercontent.com/26161297/27802711-7cf6b3c0-6060-11e7-9b9a-79d1c7335be8.jpg)
描画関連がおかしくなってしまっているようです。
私の環境ですと、Brushの形状がボタンから消えてしまいDisplayでVertices等のチェックが入っていますがモデルの方で法線などが一切表示されなくなってしまいました。

![default](https://user-images.githubusercontent.com/26161297/27802815-08d6c5d8-6061-11e7-8ba8-481c836b40ae.gif)
また、Replaceでぬりぬりすると微妙にジオメトリが変形してしまっている？ようです。

頂点の選択状況が分からないので、複数オブジェクト間コピーが正しく検証できておりません。
Unityのバージョンを2017.1.0ｆ1にアップしましたが関係あるでしょうか？

ブラシのショートカットはとても使いやすくなりました！ありがとうございます。
ブラシのMax Radiusも多分効いてると思うのですが、描画関連がおかしくなっているためこちらも確認できない状態です。

ご確認よろしくお願いします。

**Comment by i-saint** [comment]
2017.1.0f1 で問題なく動くのをこちらでは確認できています。

更新できていないファイルがある可能性があります。*Unity を起動していない状態* で Assets/UTJ/NormalPainter 以下のディレクトリを削除し、その後 NormalPainter.unitypackage を再度インポートしてもらえますでしょうか。

**Comment by i-saint** [comment]
もう一点、グラフィックス API が D3D9 になっていませんでしょうか。
D3D9 世代では使えない機能を使ってるのがブラシアイコンだったり頂点表示だったりします。

**Comment by m-sigepon** [comment]
GraphicEmulationがOpenGL ES3.0になっていたのが原因でしたorz
お騒がせしました；

**Comment by i-saint** [comment]
なるほど。解決できてよかったです！

**Comment by m-sigepon** [comment]
ホール選択なのですが、エッジだとちゃんと穴の部分が選択されていた部分がまばらにしか選択されなく上手く選択されないようです。
頭の切れ目は選択出来ているようなので、このサンプルモデルをDMでお送りしますので見てもらえるでしょうか。
![default](https://user-images.githubusercontent.com/26161297/27805061-459a3ce6-606d-11e7-98ee-263f885e9e13.jpg)

他、一通り試してみましたが複数オブジェクトの頂点合わせも上手くイケてるようです！
ブラシサイズのMAX値指定できるようになってすごく扱いやすくなりました。
一括表示非表示もチェックしやすくなって助かりました。
対応ありがとうございます！！

![default](https://user-images.githubusercontent.com/26161297/27805141-c7a5ffae-606d-11e7-93df-693401d9fe34.gif)

**Comment by i-saint** [comment]
ホール選択の問題、原因わかりました。
結論から言うと、原因はスケールが小さすぎることで、現状の回避策はスケールを上げることです。(このモデルの場合、"Use File Scale" のチェックを外して 100 倍にすれば回避できます)
次のリリースまでには直しておきます。

問題の背景を説明すると、ホール選択は内部的に一度位置が同じ頂点を接合してエッジ選択をしているのですが、この「位置が同じ頂点」の判別に問題がありました。
ご存知かもしれませんが、浮動小数点は誤差の関係でビットレベルで完璧に同一値になることは稀です。特に 3D グラフィックの場合はボーンやらなんやら行列を掛けまくるのでそれなりに誤差が出ることが多く、同じ位置かの判別は 「距離が十分に小さければ同位置ということにする」のが普通です。
で、現在ホール選択は距離 0.0001 以下を同位置と見なして接合しています。なので、今回のようなスケールが小さい場合誤認接合が起きて、その結果報告の問題となるようです…。

**Comment by m-sigepon** [comment]
>浮動小数点
そうですね、Unityにもっていって浮動小数点の影響でか頂点位置が完全に一致しないのは時々問題になっているので把握しております。
確かにブラシの設定でもモデルが小さいのが影響してたのでどうやらモデルがだいぶ小さいようですね…。
対応策実装ありがとうございます。
よろしくお願いします。

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/NormalPainter/releases
新しいバージョンをリリースしました。
ホール選択の問題が緩和されています。同じ位置かの判別の範囲をもっと小さくしただけなので根本的解決にはなってないんですが、滅多なことでは問題にならないレベルにはなっていると思います。
あとは全体的に動作が早くなってるはずです。

大きな問題が見つからなければこのまま正式リリースかな、という感じです。

**Comment by m-sigepon** [comment]
対応ありがとうございます！
今晩早速試してみたいと思います。

**Comment by m-sigepon** [comment]
最新版試してみました。
Hole選択ばっちりです！
Welding2で複数オブジェクトへの法線コピーも完璧です。
対応ありがとうございます；；

![default](https://user-images.githubusercontent.com/26161297/27972489-8b3135c6-6391-11e7-8f0c-815d06119b17.gif)

**Comment by i-saint** [comment]
よかったです！
自力では気づけそうにない問題を報告いただけてとても助かりました。おかげさまで自信を持ってリリースできそうです。

**Comment by m-sigepon** [comment]
こちらこそ、私にできるのはフィードバックぐらいなのでお力になれて幸いです。
正式リリースお待ちしております！
