### ISSUE TITLE
Feedback and feature request

### ISSUE THREAD

**Issue by ArieLeo** [unity3d-jp/NormalPainter#2]
Okay so firstly this tool are really cool, i'm impressed how fast it is. This tool should be a standard built in tool in unity.
alright some request that could make this tool more awesome for artist
1. Add support for terrain( as normal source only), this could be usefull for blending mesh to terrain
2. Projection brush mode, so we can apply the projected normal from other mesh by painting the target mesh directly.

just one issue i find, sometimes the projection doesn't work
![image](https://user-images.githubusercontent.com/6450517/28105011-5ddb046c-6710-11e7-8e95-4d9509465403.png)
I'm trying to project the underlying plane normal into selected mesh to blend them, but the normal projection not working.
but maybe it's just me do something wrong, let me know what are your thought about this.
Oh forgot to add, issue found in 2017.1 f3
Thanks

**Comment by i-saint** [comment]
> sometimes the projection doesn't work

this is how current projection works:
1. shoot rays from vertices in editing mesh to normal direction
2. if ray hits Normal Source object, get normal at hit position and set it to editing mesh

therefore, Normal Source is expected to surround editing mesh. I know it's bit confusing. this functionality is added for very specific request from my colleague.
I think what you expected is "Y direction projection". I will add it as arbitrary direction projection.

> - Add support for terrain( as normal source only)
> - Projection brush mode

I will do it as well as arbitrary direction projection.


>  i'm impressed how fast it is

I'm glad to hear that. I made a lot of effort for it.

**Comment by ArieLeo** [comment]
> therefore, Normal Source is expected to surround editing mesh. I know it's bit confusing. this functionality is added for very specific request from my colleague.

I see, that's almost similar like 3dsmax/maya normal transfer/projection system. Then it make sense :)

>I think what you expected is "Y direction projection". I will add it as arbitrary direction projection.
Yep something like that i think. Not sure which one is better, Y projection/transfer or blending normal with the normals around it that inside the spherical brush radius just like smooth brush i think but with addition of a base mesh for normal source.
>I will do it as well as arbitrary direction projection.
Glad to hear all of that man, can't wait to see your update ( Oh no rush anyway :) ).

**Comment by ArieLeo** [comment]
Oh i just remember this article, it have an example of blending custom mesh with terrain normal
[https://madewith.unity.com/en/stories/how-we-created-immortal-rednecks-sand-rendering](url)

**Comment by i-saint** [comment]
I added new projection mode and projection brush and updated package.
keep in mind: projection brush is extremely compute-intensive and maybe very slow, especially if normal source is terrain (terrain is converted to mesh internally - it can be over 500k triangles. and do ray-triangle intersection test with it)
